#define CSG_BOX 1
#define CSG_SPHERE 2

#define CSG_PLANE 3
#define CSG_TRIANGLE 4
#define CSG_CYLYNDER 5
#define CSG_CONE 6
#define CSG_TORUS 7

#define CSG_BINARY_OP_UNION 8
#define CSG_BINARY_OP_INTERSECTION 9
#define CSG_BINARY_OP_DIFFERENCE 10
#define CSG_BINARY_OP_XOR 11
#define CSG_BINARY_OP_SMOOTH_UNION 12
#define CSG_BINARY_OP_SMOOTH_INTERSECTION 13
#define CSG_BINARY_OP_SMOOTH_DIFFERENCE 14
#define CSG_UNARY_OP_REVOLVE 15
#define CSG_UNARY_OP_ELONGATE 15
#define CSG_UNARY_OP_EXTRUDE_PRE 16
#define CSG_UNARY_OP_EXTRUDE_POST 17

#define CSG_POP_DISTANCE 18
#define CSG_POP_POSITION 19

#define CSG_N_POLYGON